#!/bin/bash -eu
set -o pipefail

DEST_DIR="$1"

GIT_DEST_DIR="$(mktemp -d -t git-resource-destination.XXXXXX)"

/opt/resource/git/in "$GIT_DEST_DIR"

cd "$GIT_DEST_DIR"
export LEIN_SNAPSHOTS_IN_RELEASE=true

[[ -f project.clj ]] || { echo "There is no project.clj in the git repo." >&2; exit 1; }
### lein automatically puts deps at /root/.m2/repository
lein -U deps >&2
echo "Finished downloading files, copying to dest dir $DEST_DIR" >&2
cp -R /root/.m2/ DEST_DIR
